version: "3.0"
services: 
  ddb:
     image: mysql/mysql-server:5.7
     ports:
       - "3306:3306"
     environment:
       - "MYSQL_ROOT_PASSWORD=root"
       - "MYSQL_USER=root"
       - "MYSQL_PASSWORD=root"
       - "MYSQL_DATABASE=orange"